In [14]:
tablica = [1,2,3,4,5,8,8,6,4,3,2,2,3,4,5,6,7,8,6,5]

def funkcja2(tab1:list):
    one_list = []
    dict_of_elements = {}
    licznik = 0
    while len(tab1)>0:
        zmienna = tab1[0]
        suma_wystapien = tab1.count(tab1[0])
        if suma_wystapien > 1:
            dict_of_elements[tab1[0]] = suma_wystapien
        else:
            one_list.append(tab1[0])
        for item in tab1[:]:
            if item == zmienna:
                tab1.remove(item)
        
    print(dict_of_elements, one_list)
funkcja2(tablica)

{2: 3, 3: 3, 4: 3, 5: 3, 8: 3, 6: 3} [1, 7]


In [15]:
def sensor_read(week_day):

    week_day = week_day.lower()
    week_data = {
        "monday" : "1250",
        "tuesday" : "1405",
        "wednesday" : "1750",
        "thursday" : "1100",
        "friday" : "0800",
        "saturday" : "1225",
        "sunday" : "1355"
    }
    temp = 0
    read_data = 0

    def walidation_day(week_day):        
        if week_day in week_data:
            return int(week_data[week_day])
        else:
            return print("brak takiego odczytu")

    if isinstance(walidation_day(week_day), int): 
        read_data = walidation_day(week_day)

        if read_data >= 1400:
            temp = float(week_data[week_day])/22.5
        elif read_data > 1200 and read_data <1400:
            temp = float(week_data[week_day])/23.1
        else:
            temp = float(week_data[week_day])/23.5
        return print("Dzień: "+str( week_day.lower())+
                     "\nWskazanie czujnika: "+
                     str( week_data.get(week_day.lower()))+
                     "\nTemperatura: "+str( round(temp, 3))+"\u2103")


sensor_read("thursdaY")

Dzień: thursday
Wskazanie czujnika: 1100
Temperatura: 46.809℃


In [16]:
import random
import numpy as np
l = np.array(random.sample(range(1,100),30))
print(l)
print(l[::2])

newarr = l.reshape(3,5,2)
print(newarr)

newarr = newarr.flatten()
print(newarr)

newarr = newarr.reshape(6,5)
print(newarr)
print(newarr[::-1,::-1])

[78 69 55 43 48 58 97 53 36 23 82 20 31 15 13 25 54 72 50 19 22 16 41 39
 24 57 95 93  1 14]
[78 55 48 97 36 82 31 13 54 50 22 41 24 95  1]
[[[78 69]
  [55 43]
  [48 58]
  [97 53]
  [36 23]]

 [[82 20]
  [31 15]
  [13 25]
  [54 72]
  [50 19]]

 [[22 16]
  [41 39]
  [24 57]
  [95 93]
  [ 1 14]]]
[78 69 55 43 48 58 97 53 36 23 82 20 31 15 13 25 54 72 50 19 22 16 41 39
 24 57 95 93  1 14]
[[78 69 55 43 48]
 [58 97 53 36 23]
 [82 20 31 15 13]
 [25 54 72 50 19]
 [22 16 41 39 24]
 [57 95 93  1 14]]
[[14  1 93 95 57]
 [24 39 41 16 22]
 [19 50 72 54 25]
 [13 15 31 20 82]
 [23 36 53 97 58]
 [48 43 55 69 78]]
